export const NODE_HEIGHT_SIZES = {
  HEADER: 20,
  STATE: 16,
  STATE_SPACE_BETWEEN: 3,
  CONNECTIONS: 20,
  DESCRIPTION: 20,
};

export const NODE_WIDTH_SIZE = 160;
export const NODE_PADDING = 5;
export const NODE_CPT_PRECISION = 8;
